[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "neuro-align"
version = "0.1.0"
authors = [
  { name="Charan Sai", email="guttulacharansai@gmail.com" },
]
description = "A high-performance, memory-mapped multimodal data pipeline for neuroscience."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "h5py",
    "nibabel"
]

[project.scripts]
neuro-align = "pipeline.cli:main"

[tool.setuptools.packages.find]
include = ["pipeline*"]