name: Experanto Pipeline CI

# Tell GitHub to run this script every time you push code to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    # Boot up a Linux server in the cloud
    runs-on: ubuntu-latest

    steps:
    # Step 1: Download your repository code onto the server
    - uses: actions/checkout@v3

    # Step 2: Install Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # Step 3: Install your libraries (numpy, pytest)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the test!
    - name: Run Pytest
      run: |
        pytest